{
    "bug_type": "NULLPTR_DEREFERENCE",
    "qualifier": "`timer` could be null (from the call to `DelayPromiseAccessor.TryGetTimer(...)` on line 48) and is dereferenced.",
    "severity": "ERROR",
    "line": 50,
    "column": 17,
    "procedure": "Boolean DelayPromiseAccessor.TryCancelTimer(Task)",
    "procedure_start_line": 47,
    "file": "Engine/Accessors/DelayPromiseAccessor.cs",
    "bug_trace": [
        {
            "level": 1,
            "filename": "Engine/Accessors/DelayPromiseAccessor.cs",
            "line_number": 48,
            "column_number": 13,
            "description": "in call to `Boolean DelayPromiseAccessor.TryGetTimer(Task,Timer&)`"
        },
        {
            "level": 2,
            "filename": "Engine/Accessors/DelayPromiseAccessor.cs",
            "line_number": 17,
            "column_number": 13,
            "description": "is assigned to the null pointer"
        },
        {
            "level": 2,
            "filename": "Engine/Accessors/DelayPromiseAccessor.cs",
            "line_number": 17,
            "column_number": 13,
            "description": "assigned"
        },
        {
            "level": 1,
            "filename": "Engine/Accessors/DelayPromiseAccessor.cs",
            "line_number": 48,
            "column_number": 13,
            "description": "return from call to `Boolean DelayPromiseAccessor.TryGetTimer(Task,Timer&)`"
        },
        {
            "level": 1,
            "filename": "Engine/Accessors/DelayPromiseAccessor.cs",
            "line_number": 50,
            "column_number": 17,
            "description": "invalid access occurs here"
        }
    ],
    "key": "DelayPromiseAccessor.cs|TryCancelTimer|NULLPTR_DEREFERENCE",
    "hash": "ffc070435244d564e337feb3c61d4e58",
    "bug_type_hum": "Null Dereference"
}