    @Test
    public void testAppender() throws Exception {
        final Logger logger = ctx.getLogger();
        // Trigger the rollover
        for (int i = 0; i < 10; ++i) {
            // 30 chars per message: each message triggers a rollover
            logger.debug("This is a test message number " + i); // 30 chars:
        }
        Thread.sleep(100); // Allow time for rollover to complete

        final File dir = new File(DIR);
        assertTrue("Dir " + DIR + " should exist", dir.exists());
        assertTrue("Dir " + DIR + " should contain files", dir.listFiles().length > 0);

        final int MAX_TRIES = 20;
        for (int i = 0; i < MAX_TRIES; i++) {
            final File[] files = dir.listFiles();
            for (File file : files) {
                System.out.println(file);
            }
            if (files.length == 3) {
                for (File file : files) {
                    assertTrue("test-4.log should have been deleted",
                            Arrays.asList("test-1.log", "test-2.log", "test-3.log").contains(file.getName()));
                }
                return; // test succeeded
            }
            logger.debug("Adding additional event " + i);
            Thread.sleep(100); // Allow time for rollover to complete
        }
        fail("No rollover files found");
    }