{"hash": "799d41b339892f0c5accd40055e93c3b578b0e97", "message": "Removed the concatenation of a nested Throwable's message from all Exception classes. It was the cause of the NPE in this issue, and isn't necessary as the Exception and stacktrace contain the nested message anyway (i.e. causedBy).\nIssue: 2926982\n\n\ngit-svn-id: http://svn.code.sf.net/p/supercsv/code/trunk@225 01ba9438-b82c-4373-9247-da971c9e6a59", "file_num_lines": 72, "diff_parsed": {"added": [[44, "\t\tassertEquals(MSG, e.getMessage());"], [63, "\t\tassertEquals(MSG, e.getMessage());"]], "deleted": [[22, "\tprivate static final String CONCATENATED_MSG = THROWABLE.getMessage() + \"\\n\" + MSG;"], [45, "\t\tassertEquals(CONCATENATED_MSG, e.getMessage());"], [64, "\t\tassertEquals(CONCATENATED_MSG, e.getMessage());"]]}, "num_lines_added": 2, "num_lines_removed": 3}