{"bug_class": "PROVER", "kind": "ERROR", "bug_type": "NULL_DEREFERENCE", "qualifier": "object `AsyncExecutionTest.exec.circuitBreaker` last assigned on line 207 could be null and is dereferenced by call to `before()` at line 212.", "severity": "HIGH", "visibility": "user", "line": 212, "column": -1, "procedure": "void AsyncExecutionTest.testCompleteOrRetry()", "procedure_id": "net.jodah.failsafe.AsyncExecutionTest.testCompleteOrRetry():void.495748f3fb4910cda92554fb8837caf7", "procedure_start_line": 205, "file": "src/test/java/net/jodah/failsafe/AsyncExecutionTest.java", "bug_trace": [{"level": 0, "filename": "src/test/java/net/jodah/failsafe/AsyncExecutionTest.java", "line_number": 205, "column_number": -1, "description": "start of procedure testCompleteOrRetry()"}, {"level": 0, "filename": "src/test/java/net/jodah/failsafe/AsyncExecutionTest.java", "line_number": 207, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/RetryPolicy.java", "line_number": 42, "column_number": -1, "description": "start of procedure RetryPolicy()"}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/RetryPolicy.java", "line_number": 43, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/RetryPolicy.java", "line_number": 44, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/RetryPolicy.java", "line_number": 45, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/RetryPolicy.java", "line_number": 46, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/RetryPolicy.java", "line_number": 47, "column_number": -1, "description": "return from a call to RetryPolicy.<init>()"}, {"level": 0, "filename": "src/test/java/net/jodah/failsafe/AsyncExecutionTest.java", "line_number": 207, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/test/java/net/jodah/failsafe/AsyncExecutionTest.java", "line_number": 232, "column_number": -1, "description": "start of procedure configFor(...)"}, {"level": 1, "filename": "src/test/java/net/jodah/failsafe/AsyncExecutionTest.java", "line_number": 233, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 31, "column_number": -1, "description": "start of procedure FailsafeConfig()"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 25, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 32, "column_number": -1, "description": "return from a call to FailsafeConfig.<init>()"}, {"level": 1, "filename": "src/test/java/net/jodah/failsafe/AsyncExecutionTest.java", "line_number": 233, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 430, "column_number": -1, "description": "start of procedure with(...)"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 431, "column_number": -1, "description": "Taking true branch"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/internal/util/Assert.java", "line_number": 21, "column_number": -1, "description": "start of procedure state(...)"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/internal/util/Assert.java", "line_number": 22, "column_number": -1, "description": "Taking false branch"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/internal/util/Assert.java", "line_number": 24, "column_number": -1, "description": "return from a call to void Assert.state(boolean,String,java.lang.Object[])"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 432, "column_number": -1, "description": ""}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/internal/util/Assert.java", "line_number": 15, "column_number": -1, "description": "start of procedure notNull(...)"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/internal/util/Assert.java", "line_number": 16, "column_number": -1, "description": "Taking false branch"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/internal/util/Assert.java", "line_number": 18, "column_number": -1, "description": "return from a call to Object Assert.notNull(RetryPolicy,String)"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 432, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 433, "column_number": -1, "description": "return from a call to Object FailsafeConfig.with(RetryPolicy)"}, {"level": 1, "filename": "src/test/java/net/jodah/failsafe/AsyncExecutionTest.java", "line_number": 233, "column_number": -1, "description": "return from a call to FailsafeConfig AsyncExecutionTest.configFor(RetryPolicy)"}, {"level": 0, "filename": "src/test/java/net/jodah/failsafe/AsyncExecutionTest.java", "line_number": 207, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 23, "column_number": -1, "description": "start of procedure AsyncExecution(...)"}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 25, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AbstractExecution.java", "line_number": 28, "column_number": -1, "description": "start of procedure AbstractExecution(...)"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AbstractExecution.java", "line_number": 29, "column_number": -1, "description": ""}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/util/Duration.java", "line_number": 14, "column_number": -1, "description": "start of procedure Duration(...)"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/util/Duration.java", "line_number": 15, "column_number": -1, "description": ""}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/util/Duration.java", "line_number": 16, "column_number": -1, "description": ""}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/util/Duration.java", "line_number": 17, "column_number": -1, "description": "return from a call to Duration.<init>(long,TimeUnit)"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AbstractExecution.java", "line_number": 29, "column_number": -1, "description": ""}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/ExecutionContext.java", "line_number": 17, "column_number": -1, "description": "start of procedure ExecutionContext(...)"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/ExecutionContext.java", "line_number": 18, "column_number": -1, "description": ""}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/ExecutionContext.java", "line_number": 19, "column_number": -1, "description": "return from a call to ExecutionContext.<init>(Duration)"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AbstractExecution.java", "line_number": 30, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AbstractExecution.java", "line_number": 31, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AbstractExecution.java", "line_number": 32, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AbstractExecution.java", "line_number": 33, "column_number": -1, "description": ""}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/RetryPolicy.java", "line_number": 198, "column_number": -1, "description": "start of procedure getDelay()"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/RetryPolicy.java", "line_number": 199, "column_number": -1, "description": "return from a call to Duration RetryPolicy.getDelay()"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AbstractExecution.java", "line_number": 33, "column_number": -1, "description": ""}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/util/Duration.java", "line_number": 23, "column_number": -1, "description": "start of procedure toNanos()"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/util/Duration.java", "line_number": 23, "column_number": -1, "description": "return from a call to long Duration.toNanos()"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AbstractExecution.java", "line_number": 33, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AbstractExecution.java", "line_number": 34, "column_number": -1, "description": "return from a call to AbstractExecution.<init>(FailsafeConfig)"}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 26, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 27, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 28, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 29, "column_number": -1, "description": "return from a call to AsyncExecution.<init>(Callable,Scheduler,FailsafeFuture,FailsafeConfig)"}, {"level": 0, "filename": "src/test/java/net/jodah/failsafe/AsyncExecutionTest.java", "line_number": 207, "column_number": -1, "description": ""}, {"level": 0, "filename": "src/test/java/net/jodah/failsafe/AsyncExecutionTest.java", "line_number": 210, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 154, "column_number": -1, "description": "start of procedure completeOrRetry(...)"}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 155, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 139, "column_number": -1, "description": "start of procedure complete(...)"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 139, "column_number": -1, "description": "Taking true branch"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 140, "column_number": -1, "description": "Skipping complete(...): empty list of specs"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/AbstractExecution.java", "line_number": 78, "column_number": -1, "description": "Definition of complete(...)"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 140, "column_number": -1, "description": "Taking false branch"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 142, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 145, "column_number": -1, "description": "return from a call to boolean AsyncExecution.complete(Object,Throwable,boolean)"}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 155, "column_number": -1, "description": "Taking true branch"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 117, "column_number": -1, "description": "start of procedure isDone()"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 118, "column_number": -1, "description": "return from a call to boolean FailsafeFuture.isDone()"}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 155, "column_number": -1, "description": "Taking true branch"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 104, "column_number": -1, "description": "start of procedure isCancelled()"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 105, "column_number": -1, "description": "return from a call to boolean FailsafeFuture.isCancelled()"}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 155, "column_number": -1, "description": "Taking true branch"}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 157, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 143, "column_number": -1, "description": "start of procedure setFuture(...)"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 144, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 145, "column_number": -1, "description": "return from a call to void FailsafeFuture.setFuture(Future)"}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 158, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 167, "column_number": -1, "description": "return from a call to boolean AsyncExecution.completeOrRetry(Object,Throwable)"}, {"level": 0, "filename": "src/test/java/net/jodah/failsafe/AsyncExecutionTest.java", "line_number": 211, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 15, "column_number": -1, "description": "start of procedure isComplete()"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AbstractExecution.java", "line_number": 62, "column_number": -1, "description": "start of procedure isComplete()"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/AbstractExecution.java", "line_number": 63, "column_number": -1, "description": "return from a call to boolean AbstractExecution.isComplete()"}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 15, "column_number": -1, "description": "return from a call to boolean AsyncExecution.isComplete()"}, {"level": 0, "filename": "src/test/java/net/jodah/failsafe/AsyncExecutionTest.java", "line_number": 211, "column_number": -1, "description": "Skipping assertFalse(...): unknown method"}, {"level": 0, "filename": "src/test/java/net/jodah/failsafe/AsyncExecutionTest.java", "line_number": 212, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 114, "column_number": -1, "description": "start of procedure before()"}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 115, "column_number": -1, "description": "Taking true branch"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/CircuitBreaker.java", "line_number": 72, "column_number": -1, "description": "start of procedure allowsExecution()"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/internal/CircuitState.java", "line_number": -1, "column_number": -1, "description": "Definition of allowsExecution(...)"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/CircuitBreaker.java", "line_number": 72, "column_number": -1, "description": "return from a call to boolean CircuitBreaker.allowsExecution()"}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 115, "column_number": -1, "description": "Taking true branch"}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 116, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 117, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/CircuitBreakerOpenException.java", "line_number": 8, "column_number": -1, "description": "start of procedure CircuitBreakerOpenException()"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/CircuitBreakerOpenException.java", "line_number": 8, "column_number": -1, "description": "return from a call to CircuitBreakerOpenException.<init>()"}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 118, "column_number": -1, "description": "Taking true branch"}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 119, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 535, "column_number": -1, "description": "start of procedure handleComplete(...)"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 536, "column_number": -1, "description": "Taking false branch"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 539, "column_number": -1, "description": ""}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 615, "column_number": -1, "description": "start of procedure handleFailure(...)"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 616, "column_number": -1, "description": "Taking true branch"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 616, "column_number": -1, "description": "Taking false branch"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 621, "column_number": -1, "description": "Taking true branch"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 623, "column_number": -1, "description": ""}, {"level": 4, "filename": "src/main/java/net/jodah/failsafe/Listeners.java", "line_number": 59, "column_number": -1, "description": "start of procedure onFailure(...)"}, {"level": 4, "filename": "src/main/java/net/jodah/failsafe/Listeners.java", "line_number": 60, "column_number": -1, "description": "return from a call to void Listeners.onFailure(Object,Throwable)"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 627, "column_number": -1, "description": ""}, {"level": 4, "filename": "src/main/java/net/jodah/failsafe/Listeners.java", "line_number": 65, "column_number": -1, "description": "start of procedure onFailure(...)"}, {"level": 4, "filename": "src/main/java/net/jodah/failsafe/Listeners.java", "line_number": 66, "column_number": -1, "description": "return from a call to void Listeners.onFailure(Object,Throwable,ExecutionContext)"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 631, "column_number": -1, "description": "return from a call to void FailsafeConfig.handleFailure(Object,Throwable,ExecutionContext)"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 540, "column_number": -1, "description": ""}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 597, "column_number": -1, "description": "start of procedure handleComplete(...)"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 598, "column_number": -1, "description": "Taking true branch"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 598, "column_number": -1, "description": "Taking true branch"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 599, "column_number": -1, "description": ""}, {"level": 4, "filename": "src/main/java/net/jodah/failsafe/ExecutionContext.java", "line_number": 47, "column_number": -1, "description": "start of procedure copy()"}, {"level": 4, "filename": "src/main/java/net/jodah/failsafe/ExecutionContext.java", "line_number": 48, "column_number": -1, "description": ""}, {"level": 5, "filename": "src/main/java/net/jodah/failsafe/ExecutionContext.java", "line_number": 21, "column_number": -1, "description": "start of procedure ExecutionContext(...)"}, {"level": 5, "filename": "src/main/java/net/jodah/failsafe/ExecutionContext.java", "line_number": 22, "column_number": -1, "description": ""}, {"level": 5, "filename": "src/main/java/net/jodah/failsafe/ExecutionContext.java", "line_number": 23, "column_number": -1, "description": ""}, {"level": 5, "filename": "src/main/java/net/jodah/failsafe/ExecutionContext.java", "line_number": 24, "column_number": -1, "description": "return from a call to ExecutionContext.<init>(ExecutionContext)"}, {"level": 4, "filename": "src/main/java/net/jodah/failsafe/ExecutionContext.java", "line_number": 48, "column_number": -1, "description": "return from a call to ExecutionContext ExecutionContext.copy()"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 599, "column_number": -1, "description": ""}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 600, "column_number": -1, "description": ""}, {"level": 4, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 87, "column_number": -1, "description": "start of procedure call(...)"}, {"level": 4, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 89, "column_number": -1, "description": "Taking false branch"}, {"level": 4, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 95, "column_number": -1, "description": "return from a call to void FailsafeConfig.call(List,Object,Throwable,ExecutionContext)"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 603, "column_number": -1, "description": "Taking true branch"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 605, "column_number": -1, "description": ""}, {"level": 4, "filename": "src/main/java/net/jodah/failsafe/Listeners.java", "line_number": 35, "column_number": -1, "description": "start of procedure onComplete(...)"}, {"level": 4, "filename": "src/main/java/net/jodah/failsafe/Listeners.java", "line_number": 36, "column_number": -1, "description": "return from a call to void Listeners.onComplete(Object,Throwable)"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 609, "column_number": -1, "description": ""}, {"level": 4, "filename": "src/main/java/net/jodah/failsafe/Listeners.java", "line_number": 41, "column_number": -1, "description": "start of procedure onComplete(...)"}, {"level": 4, "filename": "src/main/java/net/jodah/failsafe/Listeners.java", "line_number": 42, "column_number": -1, "description": "return from a call to void Listeners.onComplete(Object,Throwable,ExecutionContext)"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 613, "column_number": -1, "description": "return from a call to void FailsafeConfig.handleComplete(Object,Throwable,ExecutionContext)"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeConfig.java", "line_number": 541, "column_number": -1, "description": "return from a call to void FailsafeConfig.handleComplete(Object,CircuitBreakerOpenException,AsyncExecution,boolean)"}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 120, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 121, "column_number": -1, "description": "start of procedure complete(...)"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 122, "column_number": -1, "description": "Taking true branch"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 123, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 124, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 133, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 134, "column_number": -1, "description": "Taking true branch"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 135, "column_number": -1, "description": ""}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 147, "column_number": -1, "description": "start of procedure completeFuture()"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 148, "column_number": -1, "description": "Taking false branch"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 151, "column_number": -1, "description": "Skipping completeExceptionally(...): unknown method"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 152, "column_number": -1, "description": "return from a call to void FailsafeFuture.completeFuture()"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 136, "column_number": -1, "description": ""}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/internal/util/ReentrantCircuit.java", "line_number": 83, "column_number": -1, "description": "start of procedure close()"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/internal/util/ReentrantCircuit.java", "line_number": 84, "column_number": -1, "description": "Skipping releaseShared(...): unknown method"}, {"level": 3, "filename": "src/main/java/net/jodah/failsafe/internal/util/ReentrantCircuit.java", "line_number": 85, "column_number": -1, "description": "return from a call to void ReentrantCircuit.close()"}, {"level": 2, "filename": "src/main/java/net/jodah/failsafe/FailsafeFuture.java", "line_number": 137, "column_number": -1, "description": "return from a call to void FailsafeFuture.complete(Object,CircuitBreakerOpenException,CheckedBiFunction)"}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 121, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/main/java/net/jodah/failsafe/AsyncExecution.java", "line_number": 130, "column_number": -1, "description": "return from a call to void AsyncExecution.before()"}], "key": "AsyncExecutionTest.java|testCompleteOrRetry|NULL_DEREFERENCE", "node_key": "cd1e023b8fb7f0b3653d3c5ad14bd182", "hash": "613f1ef104339044e9fbf3c910085a49", "bug_type_hum": "Null Dereference", "censored_reason": ""}